### ISSUE TITLE
Inconsistency between MOT challenge website and paper

### ISSUE THREAD

**Issue by GuangyaoZhang** [Sentient07/HeadHunter--T#11]
Hi, I am follow with interest your CroHD. It is very impressive. However, I have a question about the **Table 4** in the paper "_Tracking Pedestrian Heads in Dense Crowd_".  It shows the Headhunter--T method achieves a MOTA 63.6 and IDF1 57.1, while on MOT challenge [https://motchallenge.net/results/Head_Tracking_21/](https://motchallenge.net/results/Head_Tracking_21/) the Headhunter--T method only achieves a MOTA 57.8 and IDF1 53.9. Could you please tell me why there is an inconsistency between the two results and where is the gap. Thank you!

**Comment by Sentient07** [comment]
Refer to this note : https://github.com/Sentient07/HeadHunter--T#note- 

This is due to using different packages for evaluation. At the time of this paper submission, PyMotMetric was the library used for evaluation. Then, they migrated to a TrackEval packages. If you want to use the same evaluation scheme as performed in the paper, use PyMotMetric package referred to in the note
