### ISSUE TITLE
ModuleNotFoundError: No module named 'config.retina_cfg'

### ISSUE THREAD

**Issue by RichardoMrMu** [Sentient07/HeadHunter--T#3]
I try to test the run_new.py with my own images, but the error occurs that ModuleNotFoundError: No module named 'config.retina_cfg'. I find that config fold is not file named retian_cfg.

**Comment by scotth-tes** [comment]
Also having this issue

**Comment by scotth-tes** [comment]
Also getting this issue

**Comment by eplatero97** [comment]
I also have this error.

Further, before encountering the `config.retina_cfg`, I encountered multiple library-related errors such as those shown below:

```bash
Traceback (most recent call last):
  File "run_new.py", line 7, in <module>
    from scipy.misc import imread, imsave 
ImportError: cannot import name 'imread' from 'scipy.misc' 
------------------------------------------------------------------
﻿﻿Traceback (most recent call last):
  File "run_new.py", line 8, in <module>
    from skimage.io import imread as skimread 
ModuleNotFoundError: No module named 'skimage'
------------------------------------------------------------------
﻿﻿Traceback (most recent call last):
  File "run_new.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

> **NOTE**:  All of the errors were encountered on the conda environment that was created by running `conda env create -f env_super.yml` where I only modified line 45 and 47 to `torch==1.8.0` and `﻿torchvision==0.9.0` respectively. 

For the `scipy.misc` `ImportError`, I replaced `scipy.misc` with `imageio` to create the following line: `from imageio import imread, imsave`.  I did this replacement since this is what main scipy website recommended due to `imread` being depracated ([reference](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imread.html)).

As for the other errors, I commented all module importations for `skimage, cv2, collections, colorsys, matplotlib, itertools, h5py` since none of these modules are ever used in the actual code of `run_new.py`.

Not sure if others have encountered such problems but if they do, this will (hopefully) be a resourceful reference

**Comment by RichardoMrMu** [comment]
And I have this error in this [issue](https://github.com/Sentient07/HeadHunter/issues/5). By accidence, I find that if I use pytorch==1.4, I can load the model dict without error. It is weird.

**Comment by Sentient07** [comment]
Hello.

I encourage to use only the specified version of the packages as it is not possible for me to keep track of changes in external repository (https://github.com/Sentient07/HeadHunter/issues/3#issuecomment-924951668). That being said, if someone can fork and fix, that would be useful for others :)
